# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"\x1e\n\x0b\x42ookRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"s\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\x0c\n\x04isbn\x18\x05 \x01(\t\x12\r\n\x05pages\x18\x06 \x01(\x05\x12\r\n\x05stock\x18\x07 \x01(\x05\"\x07\n\x05\x45mpty\"-\n\x08\x42ookList\x12!\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x12.book.BookResponse\".\n\x0cStockRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\r\n\x05stock\x18\x02 \x01(\x05\" \n\rStockResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa1\x01\n\x0b\x42ookService\x12\x30\n\x07GetBook\x12\x11.book.BookRequest\x1a\x12.book.BookResponse\x12(\n\tListBooks\x12\x0b.book.Empty\x1a\x0e.book.BookList\x12\x36\n\x0bUpdateStock\x12\x12.book.StockRequest\x1a\x13.book.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=20
  _globals['_BOOKREQUEST']._serialized_end=50
  _globals['_BOOKRESPONSE']._serialized_start=52
  _globals['_BOOKRESPONSE']._serialized_end=167
  _globals['_EMPTY']._serialized_start=169
  _globals['_EMPTY']._serialized_end=176
  _globals['_BOOKLIST']._serialized_start=178
  _globals['_BOOKLIST']._serialized_end=223
  _globals['_STOCKREQUEST']._serialized_start=225
  _globals['_STOCKREQUEST']._serialized_end=271
  _globals['_STOCKRESPONSE']._serialized_start=273
  _globals['_STOCKRESPONSE']._serialized_end=305
  _globals['_BOOKSERVICE']._serialized_start=308
  _globals['_BOOKSERVICE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
